In [2]:
import pandas as pd
import numpy as np

In [3]:
df=pd.read_csv('/Users/sushilpednekar/Documents/iris - iris.csv')

In [6]:
df.head(100)

    sepal_length  sepal_width  petal_length  petal_width     species
0            5.1          3.5           1.4          0.2      setosa
1            4.9          3.0           1.4          0.2      setosa
2            4.7          3.2           1.3          0.2      setosa
3            4.6          3.1           1.5          0.2      setosa
4            5.0          3.6           1.4          0.2      setosa
..           ...          ...           ...          ...         ...
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor

[100 rows x 5 columns]

In [3]:
df['species']=df['species'].map({'setosa':0,'virginica':1, 'versicolor':2})

In [4]:
df.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species           int64
dtype: object

In [5]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [6]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [7]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width     species
count    150.000000   150.000000    150.000000   150.000000  150.000000
mean       5.843333     3.054000      3.758667     1.198667    1.000000
std        0.828066     0.433594      1.764420     0.763161    0.819232
min        4.300000     2.000000      1.000000     0.100000    0.000000
25%        5.100000     2.800000      1.600000     0.300000    0.000000
50%        5.800000     3.000000      4.350000     1.300000    1.000000
75%        6.400000     3.300000      5.100000     1.800000    2.000000
max        7.900000     4.400000      6.900000     2.500000    2.000000

In [8]:
df.shape

(150, 5)

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    int64
dtypes: float64(4), int64(1)
memory usage: 6.0 KB

In [10]:
df.min()

sepal_length    4.3
sepal_width     2.0
petal_length    1.0
petal_width     0.1
species         0.0
dtype: float64

In [11]:
df.max()

sepal_length    7.9
sepal_width     4.4
petal_length    6.9
petal_width     2.5
species         2.0
dtype: float64

In [12]:
df.mean()

sepal_length    5.843333
sepal_width     3.054000
petal_length    3.758667
petal_width     1.198667
species         1.000000
dtype: float64

In [13]:
df.median()

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
species         1.00
dtype: float64

In [14]:
df.mode()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.0          3.0           1.5          0.2        0
1           NaN          NaN           NaN          NaN        1
2           NaN          NaN           NaN          NaN        2

In [15]:
df.std()

sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
species         0.819232
dtype: float64

In [16]:
df.groupby('species')['sepal_length'].agg(['mean','median','min','max','std'])

          mean  median  min  max       std
species
0        5.006     5.0  4.3  5.8  0.352490
1        6.588     6.5  4.9  7.9  0.635880
2        5.936     5.9  4.9  7.0  0.516171

In [17]:
df2=pd.read_csv('/Users/sushilpednekar/Documents/iris - iris.csv')

In [18]:
df2.dtypes

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species             str
dtype: object

In [19]:
df2.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [20]:
# calculate and display statistical summary of petal_length for each species separately.
def stats_summry(data):
    return{
        'Mean':data.mean(),
        'STD dev': data.std(),
        '25th percentile':data.quantile(0.25),
        '50th percentile':data.quantile(0.5),
        '75th percentile':data.quantile(0.75)
    }
for sp in df2['species'].unique(): # → gets unique species names
    print('\n stats for',sp)
    print(stats_summry(df2[df2['species']==sp]['petal_length']))

 stats for setosa
{'Mean': np.float64(1.464), 'STD dev': np.float64(0.17351115943644546), '25th percentile': np.float64(1.4), '50th percentile': np.float64(1.5), '75th percentile': np.float64(1.5750000000000002)}

 stats for versicolor
{'Mean': np.float64(4.26), 'STD dev': np.float64(0.46991097723995795), '25th percentile': np.float64(4.0), '50th percentile': np.float64(4.35), '75th percentile': np.float64(4.6)}

 stats for virginica
{'Mean': np.float64(5.5520000000000005), 'STD dev': np.float64(0.5518946956639834), '25th percentile': np.float64(5.1), '50th percentile': np.float64(5.55), '75th percentile': np.float64(5.875)}

In [21]:
df.var()

sepal_length    0.685694
sepal_width     0.188004
petal_length    3.113179
petal_width     0.582414
species         0.671141
dtype: float64

In [22]:
df2[['sepal_length',]].groupby('sepal_length').mean()

Empty DataFrame
Columns: []
Index: [4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5.0, 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6.0, 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7.0, 7.1, 7.2, 7.3, 7.4, 7.6, 7.7, 7.9]